### ISSUE TITLE
Add hugo builder to buildpacks

### ISSUE THREAD

**Issue by jfmatth** [kubero-dev/kubero#107]
Would love to have Hugo as a buildpack for Kubero.

you already have the buildpack, just need to add it to the API for pulldown :)

**Comment by mms-gianni** [comment]
I had to check first. But you are right. This is missing in the default configuration.

**Comment by mms-gianni** [comment]
@jfmatth it merged now. In order to use it on your site, you will need to update your kubero UI configmap and add this snippet : 

```
      - name: Hugo
        language: GoLang
        fetch:
          repository: ghcr.io/kubero-dev/buildpacks/fetch
          tag: main
        build:
          repository: klakegg/hugo
          tag: latest
          command: hugo -D
        run:
          repository: caddy
          tag: latest
          command: caddy file-server --listen :8080 --root /app/public
```
