### ISSUE TITLE
Add Cloudflare integration

### ISSUE THREAD

**Issue by mms-gianni** [kubero-dev/kubero#234]
Add the possibility to connect to make apps publicly accessible through Cloudflare tunnels in natted environments. 

Idea by BenG ( — 14.10.2023 09:58) "help-and-support"-Channel on Discord.

Proposed Operators : 
https://github.com/adyanth/cloudflare-operator (My current favorite) 
https://github.com/STRRL/cloudflare-tunnel-ingress-controller

**Comment by bgervan** [comment]
I have played a bit with the operator approach. 

In order to reach kubero ui through a tunnel:

https://github.com/adyanth/cloudflare-operator/blob/e01ecd2dfea93bd6824169912a2ca06404d40866/docs/getting-started.md

## Create api token
The tunnel setup is required to get the api key and api tokens. 

## Deploy Operator
```
kubectl apply -k https://github.com/adyanth/cloudflare-operator/config/default
```

## Create Secrets
```
kubectl -n cloudflare-operator-system create secret generic cloudflare-secrets --from-literal CLOUDFLARE_API_TOKEN=apitoken --from-literal CLOUDFLARE_API_KEY=apikey
```

## Create ClusterTunnel file
```
# clustertunnel.yaml
apiVersion: networking.cfargotunnel.com/v1alpha1
kind: ClusterTunnel
metadata:
  name: k3s-cluster-tunnel      # The ClusterTunnel Custom Resource Name
spec:
  newTunnel:
    name: my-k8s-tunnel         # Name of your new tunnel on Cloudflare
  size: 2                       # This is the number of replicas for cloudflared
  cloudflare:
    email: asd@asd.com     # Your email used to login to the Cloudflare Dashboard
    domain: example.com         # Domain under which the tunnel runs and adds DNS entries to
    secret: cloudflare-secrets  # The secret created before
    # accountId and accountName cannot be both empty. If both are provided, Account ID is used if valid, else falls back to Account Name.
    accountName:
    accountId: your_id_from_url
  image: cloudflare/cloudflared:2023.8.2
```
### Apply
`kubectl apply -f clustertunnel.yaml`

## Create TunnelBinding to kubero ui in the right namespace

```
---
apiVersion: networking.cfargotunnel.com/v1alpha1
kind: TunnelBinding
metadata:
  name: cloudflare-tunnel-kubero
  namespace: kubero
subjects:
  - kind: Ingress
    name: kubero
tunnelRef:
  kind: ClusterTunnel
  name: k3s-cluster-tunnel
```
### Apply 
```kubectl apply -f kubero-tunnel.yaml```


The UI can be reached on kubero.example.com (the default behaviour of TunnelBinding), but the fqdn can be specified as written here: https://github.com/adyanth/cloudflare-operator/blob/e01ecd2dfea93bd6824169912a2ca06404d40866/docs/configuration.md

This fqdn approach could be used for apps as well, but for a smarter solution, the right ClusterTunnel should be selected, based on the specified fqdn, when the configs are generated. Ports are configured automatically, based on the service/ingress.
