### ISSUE TITLE
Failing to load podsize list in config section

### ISSUE THREAD

**Issue by mms-gianni** [kubero-dev/kubero#309]
Kubero Version 2.1.0

The site fails to load the form values. 

![image](https://github.com/kubero-dev/kubero/assets/2052196/77265076-4d28-47c2-8fbb-5cd582e638fe)

**Comment by mms-gianni** [comment]
**Cause**
This is caused by missing limit values in "Large" podsize. 

https://github.com/kubero-dev/kubero-operator/blob/v0.0.158/config/samples/application_v1alpha1_kubero.yaml#L235-L250
```
      - name: large
        description: 'Large (CPU: 2, Memory: 4Gi)'
        active: false
        resources:
          requests:
            memory: 4Gi
            cpu: 2000m
          limits:
            memory: 4Gi
            cpu: 2000m
```
**Fix** 
1) Add these values to kubero CRD spec.kubero.config.podSizeList
```
kubectl edit kuberoes kubero -n kubero
```

2) make sure the configmap is updated: 
```
kubectl describe configmaps kubero-config 
```

3) restart the pod
```
kubectl delete deployments.apps kubero
```
