### ISSUE TITLE
Add Planning Poker template 

### ISSUE THREAD

**Issue by mms-gianni** [kubero-dev/kubero#339]
https://github.com/axeleroy/self-host-planning-poker 

```
version: "3"
services:
  planning-poker:
    image: axeleroy/self-host-planning-poker:latest
    ports:
      - 8000:8000
    volumes:
      - planning-poker-data:/data
volumes:
  planning-poker-data: {}
 ```

Icon : https://raw.githubusercontent.com/axeleroy/self-host-planning-poker/main/assets/icon.svg 

screenshots: 
- https://raw.githubusercontent.com/axeleroy/self-host-planning-poker/main/assets/screenshot.png
- https://raw.githubusercontent.com/axeleroy/self-host-planning-poker/main/assets/screenshot-revealed.png
