### ISSUE TITLE
Issue with GKE ingress subpath 

### ISSUE THREAD

**Issue by mms-gianni** [kubero-dev/kubero#5]
Apps require a wildcard path "/*" in ingress configuration but got only "/"

I am testing some solutions for that

**Comment by mms-gianni** [comment]
Quick fix: modify path on your App definition. 

`kubectl edit kuberoapps.application.kubero.dev `


```
...
  ingress:
    annotations: {}
    className: ""
    enabled: true
    hosts:
    - host: yourtpath
      paths:
      - path: /*
...
```
