### ISSUE TITLE
Add Crossplane Addons

### ISSUE THREAD

**Issue by mms-gianni** [kubero-dev/kubero#599]
### Description

Use Crossplane to for simple Add-Creation

### Possible solution

Start with a AWS s3 Addon 

### Additional information

https://marketplace.upbound.io/providers/upbound/provider-aws-s3/v1.19.0/resources/s3.aws.upbound.io/Bucket/v1beta1 

```
apiVersion: s3.aws.upbound.io/v1beta1
kind: Bucket
metadata:
  annotations:
    meta.upbound.io/example-id: s3/v1beta1/object
  labels:
    testing.upbound.io/example-name: s3
  name: example-random
spec:
  forProvider:
    objectLockEnabled: true
    region: us-west-1
    tags:
      Name: SampleBucket
```

**Comment by mms-gianni** [comment]
https://marketplace.upbound.io/providers/upbound/provider-aws-dynamodb/v1.19.0/resources/dynamodb.aws.upbound.io/Table/v1beta1

```
apiVersion: dynamodb.aws.upbound.io/v1beta1
kind: Table
metadata:
  annotations:
    meta.upbound.io/example-id: dynamodb/v1beta1/table
  name: example
spec:
  forProvider:
    attribute:
      - name: UserId
        type: S
      - name: GameTitle
        type: S
      - name: TopScore
        type: N
    billingMode: PROVISIONED
    globalSecondaryIndex:
      - hashKey: GameTitle
        name: GameTitleIndex
        nonKeyAttributes:
          - UserId
        projectionType: INCLUDE
        rangeKey: TopScore
        readCapacity: 10
        writeCapacity: 10
    hashKey: UserId
    rangeKey: GameTitle
    readCapacity: 20
    region: us-west-1
    tags:
      Environment: production
      Name: dynamodb-table-1
    writeCapacity: 20
```

**Comment by mms-gianni** [comment]
https://marketplace.upbound.io/providers/upbound/provider-helm/v0.20.3/resources/helm.crossplane.io/Release/v1beta1 

```
apiVersion: helm.crossplane.io/v1beta1
kind: Release
metadata:
  name: wordpress-example-patched
spec:
  forProvider:
    chart:
      name: wordpress
      repository: https://charts.bitnami.com/bitnami
      version: 15.2.5
    namespace: wordpress
    patchesFrom:
      - configMapKeyRef:
          key: patch.yaml
          name: wp-patch
          namespace: wordpress
          optional: false
    set:
      - name: param1
        value: value2
    values:
      param1: value1
      param2: 1
  providerRef:
    name: helm-provider
```
