### ISSUE TITLE
Add template for Silverbuller

### ISSUE THREAD

**Issue by mms-gianni** [kubero-dev/kubero#601]
### Application Name

Silverbullet

### Describe the application

SilverBullet is a note-taking application optimized for people with a [hacker mindset](https://en.wikipedia.org/wiki/Hacker).

### URL to the application

https://silverbullet.md/

### Source code

https://github.com/silverbulletmd/silverbullet

### Application Icon

https://avatars.githubusercontent.com/u/108344757?s=48&v=4

### Link to Docker compose

sudo docker run -it -p 3000:3000 -v /path/to/my/notes:/space zefhemel/silverbullet

### Maintainer

- [ ] I am the maintainer

**Comment by mms-gianni** [comment]
```yaml
services:
  silverbullet:
    image: zefhemel/silverbullet
    restart: unless-stopped
    environment:
    - SB_USER=admin:admin
    volumes:
      - ./space:/space
    ports:
      - 3000:3000
  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
```
