### ISSUE TITLE
Add-on: OceanBase

### ISSUE THREAD

**Issue by batonac** [kubero-dev/kubero#622]
[OceanBase](https://en.oceanbase.com/) is a cloud-native distributed database that's compatible with MySQL clients. The performance is purportedly [1.9 times that of MySQL Enterprise Edition in online transaction processing (OLTP)](https://oceanbase.medium.com/tpc-h-benchmark-test-compare-oceanbase-v4-0-with-its-previous-versions-56be6f3ff1a1#:~:text=1.9%20times%20that%20of%20mysql%20enterprise%20edition%20in%20online%20transaction%20processing%20(oltp)). 

A Kubernetes operator is maintained by the core team: https://github.com/oceanbase/ob-operator

**Comment by mms-gianni** [comment]
Interesting project. I definitely want to add it. 


Found the required Cluster CRD. Not sure yet if Tenant is required too.  

https://github.com/oceanbase/ob-operator/blob/master/example/quickstart/obcluster.yaml
```
apiVersion: oceanbase.oceanbase.com/v1alpha1
kind: OBCluster
metadata:
  name: test
  namespace: default
spec:
  clusterName: obcluster
  clusterId: 1
  serviceAccount: "default"
  userSecrets:
    root: root-password
  topology:
    - zone: zone1
      replica: 1
  observer:
    image: oceanbase/oceanbase-cloud-native:4.2.1.6-106000012024042515
    resource:
      cpu: 2
      memory: 10Gi
    storage:
      dataStorage:
        storageClass: local-path
        size: 50Gi
      redoLogStorage:
        storageClass: local-path
        size: 50Gi
      logStorage:
        storageClass: local-path
        size: 20Gi
  parameters:
  - name: system_memory
    value: 1G
  - name: "__min_full_resource_pool_memory"
    value: "2147483648" # 2G
```
